import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {seedLeads,seedQuotes,seedOrders,seedTeam} from './fixtures/auto-sale-business.mjs';

test('manager save card button persists edited lead data',async()=>{
  const dom=new JSDOM('<!doctype html><div id="app"></div>',{url:'https://example.test/'});
  globalThis.window=dom.window;
  globalThis.document=dom.window.document;
  globalThis.localStorage=dom.window.localStorage;
  globalThis.sessionStorage=dom.window.sessionStorage;
  globalThis.FormData=dom.window.FormData;
  globalThis.Event=dom.window.Event;
  globalThis.CustomEvent=dom.window.CustomEvent;
  globalThis.MutationObserver=dom.window.MutationObserver;
  globalThis.HTMLFormElement=dom.window.HTMLFormElement;
  localStorage.setItem('auto-sale-leads-v2',JSON.stringify(seedLeads()));
  localStorage.setItem('auto-sale-quotes-v2',JSON.stringify(seedQuotes()));
  localStorage.setItem('auto-sale-orders-v2',JSON.stringify(seedOrders()));
  localStorage.setItem('auto-sale-team-v1',JSON.stringify(seedTeam()));
  await import('../public/auto-sale-app-v3.mjs?lead-save-action');
  const root=document.querySelector('#app');
  root.querySelector('[data-role="manager"]').click();
  root.querySelector('[data-go="leads"]').click();
  root.querySelector('[data-lead="L-103"]').click();
  const form=root.querySelector('#leadEditForm');
  assert.ok(form);
  form.elements.note.value='Сохранение работает';
  form.querySelector('button[type="submit"]').click();
  const saved=JSON.parse(localStorage.getItem('auto-sale-leads-v2')).find(x=>x.id==='L-103');
  assert.equal(saved.note,'Сохранение работает');
  dom.window.close();
});

test('new lead keeps responsible selection usable when team configuration is empty',async()=>{
  const dom=new JSDOM('<!doctype html><div id="app"></div>',{url:'https://example.test/manager-empty-team'});
  globalThis.window=dom.window;
  globalThis.document=dom.window.document;
  globalThis.localStorage=dom.window.localStorage;
  globalThis.sessionStorage=dom.window.sessionStorage;
  globalThis.FormData=dom.window.FormData;
  globalThis.Event=dom.window.Event;
  globalThis.CustomEvent=dom.window.CustomEvent;
  globalThis.MutationObserver=dom.window.MutationObserver;
  globalThis.HTMLFormElement=dom.window.HTMLFormElement;
  const assigned=seedLeads();
  localStorage.setItem('auto-sale-leads-v2',JSON.stringify(assigned));
  localStorage.setItem('auto-sale-quotes-v2','[]');
  localStorage.setItem('auto-sale-orders-v2','[]');
  localStorage.setItem('auto-sale-team-v1','[]');
  await import('../public/auto-sale-app-v3.mjs?responsible-assigned-'+Date.now());
  const root=document.querySelector('#app');
  root.querySelector('[data-role="manager"]').click();
  root.querySelector('[data-manager-new]').click();
  const field=root.querySelector('#requestForm [name="manager"]');
  assert.ok(field);
  assert.equal(field.tagName,'SELECT');
  const values=[...field.options].map(x=>x.value);
  assert.ok(values.includes('Дмитрий'));
  assert.ok(values.includes('Анна'));
  dom.window.close();
});

test('new lead always offers the three canonical responsible managers even when team state is empty',async()=>{
  const dom=new JSDOM('<!doctype html><div id="app"></div>',{url:'https://example.test/manager-empty-all'});
  globalThis.window=dom.window;
  globalThis.document=dom.window.document;
  globalThis.localStorage=dom.window.localStorage;
  globalThis.sessionStorage=dom.window.sessionStorage;
  globalThis.FormData=dom.window.FormData;
  globalThis.Event=dom.window.Event;
  globalThis.CustomEvent=dom.window.CustomEvent;
  globalThis.MutationObserver=dom.window.MutationObserver;
  globalThis.HTMLFormElement=dom.window.HTMLFormElement;
  localStorage.setItem('auto-sale-leads-v2','[]');
  localStorage.setItem('auto-sale-quotes-v2','[]');
  localStorage.setItem('auto-sale-orders-v2','[]');
  localStorage.setItem('auto-sale-team-v1','[]');
  await import('../public/auto-sale-app-v3.mjs?responsible-canonical-'+Date.now());
  const root=document.querySelector('#app');
  root.querySelector('[data-role="manager"]').click();
  root.querySelector('[data-manager-new]').click();
  const field=root.querySelector('#requestForm [name="manager"]');
  assert.ok(field);
  assert.equal(field.tagName,'SELECT');
  assert.equal(field.required,true);
  const values=[...field.options].map(x=>x.value);
  for(const manager of ['Дмитрий','Алексей','Иван'])assert.ok(values.includes(manager),manager);
  dom.window.close();
});



test('manager can delete a lead/application with explicit confirmation and local cascade cleanup',async()=>{
  const dom=new JSDOM('<!doctype html><div id="app"></div>',{url:'https://example.test/delete-lead'});
  globalThis.window=dom.window;
  globalThis.document=dom.window.document;
  globalThis.localStorage=dom.window.localStorage;
  globalThis.sessionStorage=dom.window.sessionStorage;
  globalThis.FormData=dom.window.FormData;
  globalThis.Event=dom.window.Event;
  globalThis.CustomEvent=dom.window.CustomEvent;
  globalThis.MutationObserver=dom.window.MutationObserver;
  globalThis.HTMLFormElement=dom.window.HTMLFormElement;
  const lead={id:'L-DEL',name:'Удаляемый клиент',contact:'@client',model:'BMW X5',origin:'США',budget:40000,source:'Mini App',manager:'Дмитрий',status:'В работе',priority:'Средний',createdAt:'2026-09-30T10:00:00Z',nextAction:'2026-10-01',note:'',clientCreated:true};
  const quote={id:'Q-DEL',leadId:'L-DEL',model:'BMW X5',origin:'США',status:'Согласован',version:1,total:40000,updatedAt:'2026-09-30T10:01:00Z'};
  const order={id:'O-DEL',leadId:'L-DEL',customer:'Удаляемый клиент',model:'BMW X5',manager:'Дмитрий',stage:'Выкуп',total:40000,cost:35000,paid:1000,payments:[{id:'P-DEL',amount:1000,date:'2026-09-30',method:'Банк'}],riskType:'Нет'};
  localStorage.setItem('auto-sale-leads-v2',JSON.stringify([lead]));
  localStorage.setItem('auto-sale-quotes-v2',JSON.stringify([quote]));
  localStorage.setItem('auto-sale-orders-v2',JSON.stringify([order]));
  localStorage.setItem('auto-sale-notes-v2',JSON.stringify({'L-DEL':[{id:'N-DEL',text:'note',at:'2026-09-30T10:02:00Z'}]}));
  localStorage.setItem('auto-sale-team-v1',JSON.stringify(seedTeam()));
  let deletedId='';
  window.__AUTO_SALE_DELETE_LEAD__=async id=>{deletedId=id;return{ok:true,revision:50,deleted:{lead:id,quotes:['Q-DEL'],orders:['O-DEL'],notes:1,payments:1}}};
  await import('../public/auto-sale-app-v3.mjs?delete-lead-'+Date.now());
  const root=document.querySelector('#app');
  root.querySelector('[data-role="manager"]').click();
  root.querySelector('[data-go="leads"]').click();
  root.querySelector('[data-lead="L-DEL"]').click();
  const deleteButton=root.querySelector('[data-delete-lead="L-DEL"]');
  assert.ok(deleteButton);
  deleteButton.click();
  assert.match(root.textContent,/Это действие нельзя отменить/);
  assert.match(root.textContent,/1 расчёт/);
  assert.match(root.textContent,/1 заказ/);
  const confirm=root.querySelector('[data-delete-lead-confirm="L-DEL"]');
  assert.ok(confirm);
  confirm.click();
  await new Promise(resolve=>setTimeout(resolve,0));
  await new Promise(resolve=>setTimeout(resolve,0));
  assert.equal(deletedId,'L-DEL');
  assert.deepEqual(JSON.parse(localStorage.getItem('auto-sale-leads-v2')),[]);
  assert.deepEqual(JSON.parse(localStorage.getItem('auto-sale-quotes-v2')),[]);
  assert.deepEqual(JSON.parse(localStorage.getItem('auto-sale-orders-v2')),[]);
  assert.deepEqual(JSON.parse(localStorage.getItem('auto-sale-notes-v2')),{});
  assert.equal(root.querySelector('[data-delete-lead-confirm="L-DEL"]'),null);
  dom.window.close();
});
