CREATE TABLE IF NOT EXISTS schema_meta (
  version INTEGER PRIMARY KEY,
  applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE pricing ADD COLUMN deposit_vnd INTEGER NOT NULL DEFAULT 0;

INSERT OR IGNORE INTO schema_meta (version) VALUES (4);
