import { Dispatch, SetStateAction, useEffect, useMemo, useState } from 'react';
import type { FleetState, ManagedFleetVehicle } from '../fleet/fleetManagement';
import { createService, fetchService, ServiceRecordDto, ServiceStatus, ServiceType, updateServiceStatus } from '../../api/service';

type Props={fleet:ManagedFleetVehicle[];setFleetStates:Dispatch<SetStateAction<Record<string,FleetState>>>};
const money=(v:number)=>`${new Intl.NumberFormat('ru-RU').format(v)} ₫`;
const statusLabel:Record<ServiceStatus,string>={scheduled:'Запланировано',in_progress:'В сервисе',completed:'Завершено',cancelled:'Отменено'};
const typeLabel:Record<ServiceType,string>={maintenance:'ТО',repair:'Ремонт',inspection:'Осмотр',cleaning:'Подготовка',other:'Другое'};

export function OwnerService({fleet,setFleetStates}:Props){
 const [records,setRecords]=useState<ServiceRecordDto[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[status,setStatus]=useState<'all'|ServiceStatus>('all'),[type,setType]=useState<'all'|ServiceType>('all'),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [vehicleId,setVehicleId]=useState(''),[serviceType,setServiceType]=useState<ServiceType>('maintenance'),[cost,setCost]=useState(0),[mileage,setMileage]=useState(0),[nextMileage,setNextMileage]=useState(0),[note,setNote]=useState(''),[supplier,setSupplier]=useState('UNIQ Service'),[brakes,setBrakes]=useState(true),[tires,setTires]=useState(true),[body,setBody]=useState(true);
 async function reload(){setLoading(true);const data=await fetchService();setRecords(data.records);setLoading(false)}
 useEffect(()=>{void reload()},[]);
 const active=records.filter(r=>r.status==='in_progress').length,scheduled=records.filter(r=>r.status==='scheduled').length,cost30=records.filter(r=>r.status==='completed'&&new Date(r.completedAt).getTime()>Date.now()-30*86400000).reduce((s,r)=>s+r.costVnd,0);
 const visible=useMemo(()=>records.filter(r=>{const q=query.trim().toLowerCase();return(status==='all'||r.status===status)&&(type==='all'||r.serviceType===type)&&(!q||`${r.vehicleTitle} ${r.note} ${r.supplier}`.toLowerCase().includes(q))}),[records,query,status,type]);
 const selected=fleet.find(v=>v.id===vehicleId);
 async function submit(){if(!selected)return;setBusy(true);setNotice('');try{const branchId=(selected.branchId==='branch-north'?'branch-north':'branch-center');const record=await createService({vehicleId:selected.id,branchId,status:'scheduled',serviceType,mileageKm:mileage,costVnd:cost,startedAt:new Date().toISOString(),nextServiceAt:'',nextServiceMileageKm:nextMileage,note,supplier,inspectionJson:JSON.stringify({body,brakes,tires})});setRecords(c=>[record,...c.filter(x=>x.id!==record.id)]);setOpen(false);setNotice(record.persisted?'Запись сохранена в D1.':'Запись создана в DEMO-режиме для полного каталога.');}finally{setBusy(false)}}
 async function change(record:ServiceRecordDto,next:ServiceStatus){setBusy(true);try{const saved=await updateServiceStatus(record,next);setRecords(c=>c.map(x=>x.id===saved.id?saved:x));if(next==='in_progress')setFleetStates(c=>({...c,[record.vehicleId]:'service'}));if(next==='completed'||next==='cancelled')setFleetStates(c=>({...c,[record.vehicleId]:'ready'}));setNotice(next==='completed'?'Сервис завершён: техника возвращена в парк, расход зафиксирован.':'Статус сервиса обновлён.');}finally{setBusy(false)}}
 return <section className="service-page" data-stage9-service>
  <section className="hero"><div><span className="eyebrow">СЕРВИС И СОСТОЯНИЕ ПАРКА</span><h1>ТО, ремонт и осмотры.</h1><p>Пробег, расходы и готовность техники к аренде — в одной системе владельца.</p></div><div className="service-hero-card"><b>{active}</b><span>сейчас в сервисе</span><small>{money(cost30)} расходов за 30 дней</small></div></section>
  <section className="metrics"><div className="metric"><span>В сервисе</span><b>{active}</b></div><div className="metric"><span>Запланировано</span><b>{scheduled}</b></div><div className="metric"><span>Завершено</span><b>{records.filter(r=>r.status==='completed').length}</b></div><div className="metric"><span>Расходы 30 дней</span><b>{money(cost30)}</b></div></section>
  <section className="section"><div className="section-head"><div><span className="eyebrow">ЖУРНАЛ</span><h2>Сервисные работы</h2></div><button className="primary" data-add-service onClick={()=>setOpen(true)}>+ Новая запись</button></div>
   <div className="service-toolbar"><input data-service-search placeholder="Поиск по технике, работе, сервису" value={query} onChange={e=>setQuery(e.target.value)}/><select data-service-status value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">Все статусы</option><option value="scheduled">Запланировано</option><option value="in_progress">В сервисе</option><option value="completed">Завершено</option><option value="cancelled">Отменено</option></select><select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="all">Все работы</option><option value="maintenance">ТО</option><option value="repair">Ремонт</option><option value="inspection">Осмотр</option><option value="cleaning">Подготовка</option><option value="other">Другое</option></select></div>
   {loading?<div className="empty">Загружаем сервис…</div>:<div className="service-list">{visible.map(r=><article key={r.id} data-service-record={r.id}><div><span className={`service-status ${r.status}`}>{statusLabel[r.status]}</span><h3>{r.vehicleTitle}</h3><p>{typeLabel[r.serviceType]} · {r.mileageKm?`${r.mileageKm.toLocaleString('ru-RU')} км · `:''}{r.supplier||'UNIQ Service'}</p><small>{r.note||'Без комментария'}</small></div><div className="service-cost"><span>Расход</span><b>{money(r.costVnd)}</b>{r.nextServiceMileageKm?<small>След. ТО: {r.nextServiceMileageKm.toLocaleString('ru-RU')} км</small>:null}</div><div className="service-actions">{r.status==='scheduled'?<button className="primary" data-service-start={r.id} disabled={busy} onClick={()=>change(r,'in_progress')}>В сервис</button>:null}{r.status==='in_progress'?<button className="primary" data-service-complete={r.id} disabled={busy} onClick={()=>change(r,'completed')}>Вернуть в парк</button>:null}{r.status==='scheduled'?<button className="secondary" disabled={busy} onClick={()=>change(r,'cancelled')}>Отменить</button>:null}</div></article>)}</div>}
   {notice?<div className="owner-notice">{notice}</div>:null}
  </section>
  {open?<div className="modal-bg" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><section className="modal service-editor" data-service-editor><button className="modal-x" onClick={()=>setOpen(false)}>×</button><span className="eyebrow">НОВАЯ СЕРВИСНАЯ ЗАПИСЬ</span><h2>Поставить технику на контроль</h2><div className="form-grid"><label>Техника<select data-service-vehicle value={vehicleId} onChange={e=>setVehicleId(e.target.value)}><option value="">Выберите технику</option>{fleet.filter(v=>!v.archivedAt).map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label><label>Тип работы<select data-service-type value={serviceType} onChange={e=>setServiceType(e.target.value as ServiceType)}><option value="maintenance">ТО</option><option value="repair">Ремонт</option><option value="inspection">Осмотр</option><option value="cleaning">Подготовка</option><option value="other">Другое</option></select></label><label>Пробег, км<input type="number" value={mileage||''} onChange={e=>setMileage(Number(e.target.value))}/></label><label>Следующее ТО, км<input type="number" value={nextMileage||''} onChange={e=>setNextMileage(Number(e.target.value))}/></label><label>Стоимость, ₫<input data-service-cost type="number" value={cost||''} onChange={e=>setCost(Number(e.target.value))}/></label><label>Сервис / исполнитель<input value={supplier} onChange={e=>setSupplier(e.target.value)}/></label></div><label>Комментарий<textarea data-service-note value={note} onChange={e=>setNote(e.target.value)} placeholder="Что проверяем или ремонтируем"/></label><div className="inspection-checks" data-service-inspection><label><input type="checkbox" checked={body} onChange={e=>setBody(e.target.checked)}/>Кузов / пластик</label><label><input type="checkbox" checked={brakes} onChange={e=>setBrakes(e.target.checked)}/>Тормоза</label><label><input type="checkbox" checked={tires} onChange={e=>setTires(e.target.checked)}/>Шины / колёса</label></div><button className="primary wide" data-save-service disabled={busy||!vehicleId} onClick={submit}>{busy?'Сохраняем…':'Создать запись'}</button></section></div>:null}
 </section>;
}
