openapi: 3.0.0
info:
  title: AUTO SALE demo
  version: 1.0.0
paths:
  /{proxy+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bba01u6g86lg2q49p34d
      parameters:
        - explode: false
          in: path
          name: proxy
          required: false
          schema:
            default: '-'
            type: string
          style: simple
