import type { D1DatabaseLike } from '../db/bootstrap.js';

type Env={DB?:D1DatabaseLike;STAFF_API_KEY?:string;DEMO_MODE?:string};
const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-uniq-admin-key,x-uniq-demo-role','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});
const text=(v:unknown)=>typeof v==='string'?v.trim():'';
const num=(v:unknown)=>Number.isFinite(Number(v))?Math.max(0,Math.round(Number(v))):0;
const isOwner=(r:Request,e:Env)=>Boolean(e.STAFF_API_KEY&&r.headers.get('x-uniq-admin-key')===e.STAFF_API_KEY)||(e.DEMO_MODE==='true'&&r.headers.get('x-uniq-demo-role')==='owner');
const statuses=new Set(['scheduled','in_progress','completed','cancelled']);
const types=new Set(['maintenance','repair','inspection','cleaning','other']);
async function body(r:Request){try{return await r.json() as Record<string,unknown>}catch{return null}}
function mapRow(row:Record<string,unknown>){return{ id:String(row.id??''),vehicleId:String(row.vehicle_id??''),vehicleTitle:String(row.vehicle_title??''),branchId:String(row.branch_id??''),branchName:String(row.branch_name??''),status:String(row.status??'scheduled'),serviceType:String(row.service_type??'maintenance'),mileageKm:Number(row.mileage_km??0),costVnd:Number(row.cost_vnd??0),startedAt:String(row.started_at??''),completedAt:String(row.completed_at??''),nextServiceAt:String(row.next_service_at??''),nextServiceMileageKm:Number(row.next_service_mileage_km??0),note:String(row.note??''),supplier:String(row.supplier??''),inspectionJson:String(row.inspection_json??'{}'),persisted:true};}
async function list(env:Env){if(!env.DB)return json({error:'persistence_not_configured'},503);const rows=await env.DB.prepare(`SELECT s.*,COALESCE(v.title,TRIM(v.brand||' '||v.model),s.vehicle_id) vehicle_title,COALESCE(b.name,'') branch_name FROM service_records s LEFT JOIN vehicles v ON v.id=s.vehicle_id LEFT JOIN branches b ON b.id=s.branch_id ORDER BY s.started_at DESC LIMIT 200`).all<Record<string,unknown>>();const records=(rows.results??[]).map(mapRow);const since=new Date(Date.now()-30*86400000).toISOString();const completed30d=records.filter(x=>x.status==='completed'&&x.completedAt>=since);return json({records,summary:{inService:records.filter(x=>x.status==='in_progress').length,scheduled:records.filter(x=>x.status==='scheduled').length,completed30d:completed30d.length,cost30dVnd:completed30d.reduce((s,x)=>s+x.costVnd,0),dueSoon:records.filter(x=>x.status==='scheduled').length},persisted:true});}
async function create(request:Request,env:Env){if(!env.DB)return json({error:'persistence_not_configured'},503);const p=await body(request);if(!p)return json({error:'invalid_json'},400);const id=text(p.id)||crypto.randomUUID(),vehicleId=text(p.vehicleId),branchId=text(p.branchId),status=text(p.status)||'scheduled',serviceType=text(p.serviceType),startedAt=text(p.startedAt)||new Date().toISOString();if(!vehicleId||!types.has(serviceType)||!statuses.has(status))return json({error:'invalid_service'},400);const vehicle=await env.DB.prepare('SELECT id,COALESCE(title,TRIM(brand||\' \'||model)) title FROM vehicles WHERE id=? LIMIT 1').bind(vehicleId).first<{id:string;title:string}>();if(!vehicle)return json({error:'vehicle_not_synced_to_d1'},404);await env.DB.prepare(`INSERT INTO service_records (id,vehicle_id,branch_id,status,service_type,mileage_km,cost_vnd,started_at,next_service_at,next_service_mileage_km,note,supplier,inspection_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,vehicleId,branchId||null,status,serviceType,num(p.mileageKm),num(p.costVnd),startedAt,text(p.nextServiceAt)||null,num(p.nextServiceMileageKm)||null,text(p.note),text(p.supplier),text(p.inspectionJson)||'{}',new Date().toISOString(),new Date().toISOString()).run();if(status==='in_progress'){await env.DB.prepare("UPDATE vehicles SET status='service',updated_at=? WHERE id=?").bind(new Date().toISOString(),vehicleId).run();await env.DB.prepare(`INSERT OR REPLACE INTO vehicle_availability_blocks (id,vehicle_id,branch_id,block_type,starts_at,ends_at,source_entity_id,note,created_at) VALUES (?,?,?,'service',?,?,?,?,?,?)`).bind(`service-block-${id}`,vehicleId,branchId||null,startedAt,'2999-12-31',id,text(p.note),new Date().toISOString()).run();}const row=await env.DB.prepare(`SELECT s.*,COALESCE(v.title,TRIM(v.brand||' '||v.model),s.vehicle_id) vehicle_title,COALESCE(b.name,'') branch_name FROM service_records s LEFT JOIN vehicles v ON v.id=s.vehicle_id LEFT JOIN branches b ON b.id=s.branch_id WHERE s.id=?`).bind(id).first<Record<string,unknown>>();return json({record:mapRow(row??{}),persisted:true},201);}
async function update(request:Request,env:Env,id:string){if(!env.DB)return json({error:'persistence_not_configured'},503);const p=await body(request),status=text(p?.status);if(!statuses.has(status))return json({error:'invalid_status'},400);const current=await env.DB.prepare('SELECT * FROM service_records WHERE id=? LIMIT 1').bind(id).first<Record<string,unknown>>();if(!current)return json({error:'service_not_found'},404);const now=new Date().toISOString(),vehicleId=String(current.vehicle_id??''),branchId=String(current.branch_id??'');await env.DB.prepare('UPDATE service_records SET status=?,completed_at=CASE WHEN ?=\'completed\' THEN ? ELSE completed_at END,updated_at=? WHERE id=?').bind(status,status,now,now,id).run();if(status==='in_progress'){await env.DB.prepare("UPDATE vehicles SET status='service',updated_at=? WHERE id=?").bind(now,vehicleId).run();await env.DB.prepare(`INSERT OR REPLACE INTO vehicle_availability_blocks (id,vehicle_id,branch_id,block_type,starts_at,ends_at,source_entity_id,note,created_at) VALUES (?,?,?,'service',?,?,?,?,?,?)`).bind(`service-block-${id}`,vehicleId,branchId||null,String(current.started_at??now),'2999-12-31',id,String(current.note??''),now).run();}
if(status==='completed'){await env.DB.prepare("UPDATE vehicles SET status='manager_confirmation',odometer_km=MAX(odometer_km,?),last_service_at=?,next_service_at=?,next_service_mileage_km=?,updated_at=? WHERE id=?").bind(num(current.mileage_km),now,current.next_service_at||null,current.next_service_mileage_km||null,now,vehicleId).run();await env.DB.prepare('DELETE FROM vehicle_availability_blocks WHERE source_entity_id=?').bind(id).run();const cost=num(current.cost_vnd);if(cost>0)await env.DB.prepare(`INSERT INTO transactions (id,branch_id,vehicle_id,type,status,amount_vnd,method,occurred_at,note,created_at) VALUES (?,? ,?,'service_expense','completed',?,'service',?,?,?)`).bind(crypto.randomUUID(),branchId||null,vehicleId,cost,now,`Service ${id}`,now).run();}
if(status==='cancelled')await env.DB.prepare('DELETE FROM vehicle_availability_blocks WHERE source_entity_id=?').bind(id).run();const row=await env.DB.prepare(`SELECT s.*,COALESCE(v.title,TRIM(v.brand||' '||v.model),s.vehicle_id) vehicle_title,COALESCE(b.name,'') branch_name FROM service_records s LEFT JOIN vehicles v ON v.id=s.vehicle_id LEFT JOIN branches b ON b.id=s.branch_id WHERE s.id=?`).bind(id).first<Record<string,unknown>>();return json({record:mapRow(row??{}),persisted:true});}
export async function handleServiceRequest(request:Request,env:Env,url:URL):Promise<Response|null>{if(!url.pathname.startsWith('/api/owner/service'))return null;if(!isOwner(request,env))return json({error:'unauthorized'},401);if(url.pathname==='/api/owner/service'&&request.method==='GET')return list(env);if(url.pathname==='/api/owner/service'&&request.method==='POST')return create(request,env);const m=url.pathname.match(/^\/api\/owner\/service\/([^/]+)$/);if(m&&request.method==='PATCH')return update(request,env,decodeURIComponent(m[1]??''));return json({error:'not_found'},404);}
